import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner'
import Header from '../components/header'
import styles from '../styles/Home.module.css'
import HomePage from './HomePage'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Assigntment WEB209-FW2-NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HomePage/>
      </main>
    </div>
  )
}

export default Home
